version: '3.8'

services:
  web:
    build: .
    image: web-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./database:/app/database
    environment:
      - DATABASE_URL=sqlite:///./database/database.db
    deploy:
      replicas: 3
    expose:
      - "8000"

  nginx-balancer:
    image: nginx
    container_name: nginx-balancer
    restart: unless-stopped
    volumes:
      - ./nginx-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8080:80"

  nginx-html:
    image: nginx
    container_name: nginx-html
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - nginx-balancer
    ports:
      - "8081:80"
