version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
      - ./database:/app/database
    environment:
      - DATABASE_URL=sqlite:///./database/database.db
