name: loveapp
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterflow_ui: ^0.3.1
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  collection: 1.18.0
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  flutter_svg: 2.0.9
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  intl: 0.19.0
  json_path: 0.7.2
  mask_text_input_formatter: 2.9.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  percent_indicator: 4.2.2
  pin_code_fields: 8.0.1
  provider: 6.1.2
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sqflite: 2.2.6
  timeago: 3.6.1
  url_launcher: 6.3.0
  url_launcher_android: 6.3.4
  url_launcher_ios: 6.3.1
  url_launcher_platform_interface: 2.3.2

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/images/iPhone_14_&_15_Pro_-_29.jpg
  fonts:
    - family: Miratrix
      fonts:
        - asset: assets/fonts/Miratrix/Miratrix-Normal.otf
          weight: 400

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
