name: Deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production

    steps:
      - name: Connect to ssh
        run: |
          ssh root@${{ secrets.SSH_HOST }}
          ${{secrets.SSH_PRIVATE_KEY}}

      - name: Stop docker container
        run: | 
          docker stop docker-db
      - name: Delete docker container
        run: | 
          docker delete docker-db
      - name: Pull the latest image
        run: | 
          docker pull $REGISTRY/${{ github.repository }}:docker-db
      - name: Deploy container
        run: | 
          docker run -d --name docker-db -p 8080:8000 $REGISTRY/${{ github.repository }}:docker-db
      
        
      