name: Build and Run Docker

on:
  push:
    branches:
      - docker-db
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t loveapp-db .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 loveapp-db

      - name: Wait for the app to start
        run: |
          sleep 10
          curl http://localhost:8000
