name: Build and Run Docker-Compose

on:
  push:
    branches:
      - docker-db
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build services
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d

      - name: Wait for the app to start
        run: |
          sleep 10
          curl https://whaleopop.github.io/LoveApp/