name: publish

on: [push]

jobs:
  publish-docker-place-image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the docker-place Docker image
      run: |
        docker build . --tag ghcr.io/whaleopop/loveapp-docker-place:docker-place
        docker run ghcr.io/whaleopop/loveapp-docker-place:docker-place
        docker push ghcr.io/whaleopop/loveapp-docker-place:docker-place
